version: '3.8'
services:
  db:
    image: postgres:13-alpine
    volumes:
      - db_volume:/var/lib/postgresql/data/
    env_file:
      - ./.env
  backend:
    image: elhombreinvisible/foodgram:latest
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - static_value:/media/
      - media_value:/static/
    env_file:
      - ./.env
  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - db
      - backend
  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/ #или result_build???
      - ../docs/:/usr/share/nginx/html/api/docs/
    depends_on:
      - db
      - backend

volumes:
  db_volume:
  static_value:
  media_value: