name: foodgram-deploy
on:
 push:
  branches: [ "master" ]
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install Test env and flake8
        run: |
          python -m pip install --upgrade pip
          pip install -r ./backend/requirements.txt
          pip install flake8 pep8-naming flake8-return flake8-isort
      - name: flake8 tests
        run: |
          cd backend/
          python -m flake8

  push_to_dockerhub:
    name: Build and push to Docker Hub
    runs_on: ubuntu-latest
    needs: tests
    steps:
      - name: Check out
        uses: actions/checkout@v3
      - name: Set up Docker Buildx 
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./backend/
          dockerfile: ./backend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/foodgram:latest

  send_message:
    runs-on: ubuntu-latest
    needs: tests
    steps:
    - name: send message
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: ${{ github.workflow }} успешно выполнен!
